spring.application.name=customer-front-theymeleaf-app
spring.datasource.url=jdbc:h2:mem:customers-db
spring.h2.console.enabled=true
spring.mvc.format.date=d/M/yyyy
server.port=8787

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${token.google}
spring.security.oauth2.client.provider.google.user-name-attribute=email

spring.security.oauth2.client.registration.github.client-id=${GOOGLE_GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${token.github}
spring.security.oauth2.client.provider.github.user-name-attribute=login

spring.security.oauth2.client.registration.keycloak.client-name=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=sdia-customer-app
spring.security.oauth2.client.registration.keycloak.client-secret=${token.keycloak}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,offline_access
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8787/login/oauth2/code/sdia-customer-app
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/sdia-realm

spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ebank-realm