spring.application.name=inventory-service
spring.datasource.url=jdbc:h2:mem:products-db
spring.h2.console.enabled=true
server.port=8585

#configurer une API Spring Boot comme Resource Server OAuth2, en utilisant JWT émis par Keycloak:
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/sdia-realm
spring.security.oauth2.resourceserver.jwt.jwk-se-uri=http://localhost:8080/realms/sdia-realm/protocol/openid-connect/certs